"use client"

import React, { useState, useEffect } from 'react';
import NewTask from './NewTask';
import TaskItem from './TaskItem';
import { collection, query, onSnapshot, doc, updateDoc, addDoc, deleteDoc } from 'firebase/firestore';
import { db } from '../firebase/firebase';

//import { v4 as uuidv4 } from 'uuid';



type Task = {
  id: string;
  text: string;
  isCompleted: boolean;
};

const TaskList = () => {
    const [tasks, setTasks] = useState<Task[]>([]);

    //Create task
    const createTask = async (text: string) => {
        try {
            // Create a new task object without an ID
            const newTask = {
                text,
                isCompleted: false
            };

            // Add a new document in Firestore
            const docRef = await addDoc(collection(db, 'tasks'), newTask);
            // Update local state with the new task including the ID generated by Firestore
            setTasks(prevTasks => [{ ...newTask, id: docRef.id }, ...prevTasks]);
        } catch (error) {
            console.error("Error adding document: ", error);
        }
    };


    //Read task from firebase
    useEffect(() => {
        const q = query(collection(db, 'tasks'));
        const listTasks = onSnapshot(q, (querySnapshot) => {
            let tasksArr: Task[] = [];
            querySnapshot.forEach((doc) => {
                const taskData = doc.data() as Task; // Cast the data to the Task type
                tasksArr.push({ ...taskData, id: doc.id });
            });
            setTasks(tasksArr);
        });

        return listTasks;
    }, []);

    //Update(edit) tasks in firebase
    const editTask = async (id: string, newText: string) => {
        // Create a reference to the task document
        const taskDocRef = doc(db, 'tasks', id);
    
        try {
            // Update the document in Firestore
            await updateDoc(taskDocRef, { text: newText });
    
            // Update the task in the local state
            setTasks(prevTasks =>
                prevTasks.map(task => 
                    task.id === id ? {...task, text: newText } : task
                )
            );
        } catch (error) {
            // Handle any errors
            console.error("Error updating document: ", error);
        }
    };

    //Toggle Complete
    const toggleComplete =async (id: string) => {
      try{
        // Find the task to be updated in the local state
        const taskToToggle = tasks.find(task => task.id === id);
        if(!taskToToggle){
            throw new Error('Task not found');
        }

        // Calculate the new completion status
        const newIsCompleted = !taskToToggle.isCompleted;
        // Create a reference to the task document
        const taskDocRef = doc(db, 'tasks', id);
        // Update the document in Firestore
        await updateDoc(taskDocRef, { isCompleted: newIsCompleted });
        // Update the task in the local state
        setTasks(prevTasks =>
            prevTasks.map(task => 
                task.id === id ? {...task, isCompleted: newIsCompleted} : task
            )
        );
      } catch (error) {
        console.error('Error updating document: ', error);
      }
    };


    //Delete task
    const deleteTask = async (id: string) => {
        try {
            // Create a reference to the task document
            const taskDocRef = doc(db, 'tasks', id);
    
            // Delete the document from Firestore
            await deleteDoc(taskDocRef);
    
            // Update the local state to remove the task
            setTasks(prevTasks => prevTasks.filter(task => task.id !== id));
        } catch (error) {
            // Handle any errors
            console.error("Error deleting document: ", error);
        }
    };





    //OLD CREATE TASK
    // const addTask = (text: string) => {
    //     const newTask: Task = {
    //         id: uuidv4(),
    //         text,
    //         isCompleted: false
    //     };
    //     setTasks(prevTasks => [newTask, ...prevTasks]);
    // };

    // OLD TOGGLECOMPLETE
    // const toggleComplete = (id: string) => {
    //     setTasks(prevTasks =>
    //         prevTasks.map(task => 
    //             task.id === id ? {...task, isCompleted: !task.isCompleted} : task
    //         )
    //     );
    // };

    // OLD EDIT
    // const editTask = (id: string, newText: string) => {
    //     setTasks(prevTasks =>
    //         prevTasks.map(task => 
    //             task.id === id ? {...task, text: newText } : task
    //         )
    //     );
    // };
    
    //OLD DELETE
        // const deleteTask = (id: string) => {
    //     setTasks(prevTasks => prevTasks.filter(task => task.id !== id));
    // };

    return(
        <div>
            <h1>To-Do List</h1>
            <NewTask createTask={createTask} />
            {tasks.map((task) => (
                <TaskItem
                    key={task.id}
                    task={task}
                    toggleComplete={toggleComplete}
                    deleteTask={deleteTask}
                    editTask={editTask} 
                />
            ))}
        </div>
    )
};

export default TaskList;